using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace HuaweiARUnitySDK
{
    public enum CloudServiceState
    {
        HWAR_CLOUD_SERVICE_NORMAL = 10000,
        HWAR_CLOUD_SERVICE_ERROR_NETWORK_UNAVAILABLE = 10001,
        HWAR_CLOUD_SERVICE_ERROR_CLOUD_SERVICE_UNAVAILABLE = 10002,
        HWAR_CLOUD_SERVICE_ERROR_NOT_AUTHORIZED = 10003,
        HWAR_CLOUD_SERVICE_ERROR_SERVER_VERSION_TOO_OLD = 10004,
        HWAR_CLOUD_SERVICE_ERROR_TIME_EXHAUSTED = 10005,
        HWAR_CLOUD_SERVICE_ERROR_INTERNAL = 10006,
        HWAR_CLOUD_IMAGE_ERROR_IMAGE_GALLERY_INVALID = 20001,
        HWAR_CLOUD_IMAGE_ERROR_IMAGE_RECOGNIZE_FAILE = 20002,
        HWAR_CLOUD_OBJECT_ERROR_OBJECT_MODEL_INVALID = 30001,
        HWAR_CLOUD_OBJECT_ERROR_OBJECT_RECOGNIZE_FAILE = 30002
    }
}