namespace HuaweiARInternal
{
    public enum NDKARStatus
    {
        HWAR_SUCCESS = 0,
        HWAR_ERROR_INVALID_ARGUMENT = -1,
        HWAR_ERROR_FATAL = -2,
        HWAR_ERROR_SESSION_PAUSED = -3,
        HWAR_ERROR_SESSION_NOT_PAUSED = -4,
        HWAR_ERROR_NOT_TRACKING = -5,
        HWAR_ERROR_TEXTURE_NOT_SET = -6,
        HWAR_ERROR_MISSING_GL_CONTEXT = -7,
        HWAR_ERROR_UNSUPPORTED_CONFIGURATION = -8,
        HWAR_ERROR_CAMERA_PERMISSION_NOT_GRANTED = -9,
        HWAR_ERROR_DEADLINE_EXCEEDED = -10,
        HWAR_ERROR_RESOURCE_EXHAUSTED = -11,
        HWAR_ERROR_NOT_YET_AVAILABLE = -12,
        HWAR_ERROR_CAMERA_NOT_AVAILABLE = -13,
        HWAR_UNAVAILABLE_AREXECUTOR_NOT_INSTALLED = -100,
        HWAR_UNAVAILABLE_DEVICE_NOT_COMPATIBLE = -101,
        HWAR_UNAVAILABLE_APK_TOO_OLD = -103,
        HWAR_UNAVAILABLE_SDK_TOO_OLD = -104,
        HWAR_UNAVAILABLE_USER_DECLINED_INSTALLATION = -105,

        HWAR_UNAVAILABLE_EMUI_NOT_CAPABLE = -1000,
        HWAR_UNAVAILABLE_CONNECT_SERVER_TIME_OUT = -1001,
    }
}
